name: php-build-actions-workflow
on:
  push:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: php-actions/composer@v6
      with:
        php_version: "8.4"
        php_extensions: bcmath
        working_dir: ./app
        
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: evercoolhk.com
        username: evercoolhk
        password: ${{ secrets.PASSWORD }}
        local-dir: app/
        server-dir: /www/api/
    # directly put in root directory of api.evercoolhk.com
